### PR TITLE
Coerce boxed instances to their primitive values for serialization.

### LINKED ISSUE #57: Boxed primitives are stored as Serializable
Given this:
```
public abstract Integer foo();
```
The plugin generates this:
```
dest.writeSerializable(foo());
```

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #57.

### CODE REVIEW

**Comment by rharter** [comment]
Unless I'm missing it, this doesn't take into account nullable boxed primitives.  Would need tests and checks for `@Nullable Boolean foo()`, etc.

**Comment by JakeWharton** [comment]
See the very bottom of the diff for an existing `@Nullable` primitive.

**Comment by rharter** [comment]
good point.

**Comment by rharter** [comment]
Thanks!

**Pull request merged**
