### PR TITLE
Support immutable collections

### LINKED ISSUE #118: ArrayList cannot be converted to ImmutableList
Hi,
I'm getting error
`Error:(18, 51) error: incompatible types: ArrayList cannot be converted to ImmutableList<String>`

When I try to rebuild this sample class from official [AutoValue sample for collection](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#collection)

```@AutoValue
public abstract class Animal implements Parcelable {
    public abstract String name();
    public abstract int numberOfLegs();
    public abstract ImmutableList<String> countries();

    public static Builder builder() {
        return new AutoValue_Animal.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setName(String value);
        public abstract Builder setNumberOfLegs(int value);
        public abstract Builder setCountries(List<String> value);
        public abstract Animal build();
    }
}
```
This class is similar to example but only three things changed:
1. Added "implements Parcelable"
2. Changed "ImmutableSet" to "ImmutableList"
3. Changed Set<String> to List<String>

This error is shown in generated class  AutoValue_Animal, method createFromParcel as below
```
final class AutoValue_Animal extends $AutoValue_Animal {
  public static final Parcelable.Creator<AutoValue_Animal> CREATOR = new Parcelable.Creator<AutoValue_Animal>() {
    @Override
    @SuppressWarnings("unchecked")
    public AutoValue_Animal createFromParcel(Parcel in) {
      return new AutoValue_Animal(
          in.readString(),
          in.readInt(),
          (ImmutableList<String>) in.readArrayList(String.class.getClassLoader())
      );
    }
    @Override
    public AutoValue_Animal[] newArray(int size) {
      return new AutoValue_Animal[size];
    }
  };

  AutoValue_Animal(String name, int numberOfLegs, ImmutableList<String> countries) {
    super(name, numberOfLegs, countries);
  }

  @Override
  public void writeToParcel(Parcel dest, int flags) {
    dest.writeString(name());
    dest.writeInt(numberOfLegs());
    dest.writeList(countries());
  }

  @Override
  public int describeContents() {
    return 0;
  }
}
```

Note: If I keep ImmutableSet and Set it compiles successfully.

Appreciate help to resolve this issue.

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #118, closes #105

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@rharter Any thoughts?

**Comment by SUPERCILEX** [comment]
Awesome, thanks!

@rharter Unfortunately, I just tested it IRL and it doesn't work. Looks like the the guava packages are being mapped to `autovaluemoshi.shaded.com.google.common.collect` by the shadow jar thing, leading to the types not being recognized. Why is that being done?

**Comment by SUPERCILEX** [comment]
@rharter Hmmm, I don't get the point of the shadow jar at all. Can it just be removed?

**Comment by SUPERCILEX** [comment]
The good news is that it all works (runtime included) without the shadow stuff.

**Comment by rharter** [comment]
Wait, shadow changes the plain strings?

**Comment by rharter** [comment]
We can't remove it. When something else on the annotation processor classpath changes the guava version it causes problems, so we have to shade it so we can keep using our own. The solution is to configure the Shadow Gradle plugin to ignore those plain strings that are used to reference the classes.

**Comment by SUPERCILEX** [comment]
Yup, it does. (I guess it's just a find/replace). Working on a hacky fix.

**Comment by SUPERCILEX** [comment]
See #146

**Pull request merged**
