### PR TITLE
Reverts code to bypass `Parcel.writeParcelables()` method.

### PR DESCRIPTION
**Pull request by rharter**

### CODE REVIEW

**Comment by NightlyNexus** [comment]
Looks good to me.

**Comment by JakeWharton** [comment]
Can either of you remind me why we reverted this functionality?

**Comment by JakeWharton** [comment]
Was it polymorphism? Non-final types need `writeParcelable` to encode the implementation type.

**Comment by rharter** [comment]
IIRC it was the polymorphism.  I think there was some conversation around it somewhere. let me look.

**Comment by rharter** [comment]
[Here](https://github.com/rharter/auto-value-parcel/pull/77#issuecomment-227750012) it is:

> I think this highlights a larger problem with this entire approach. When using writeParcelable and readParcelable, the Parcel class will write the class name from which to get the Creator, then use that value when it reads. By bypassing that with this approach, we have basically prevented the user from being able to use subclasses of their properties.
>
>In your example above, if the user sets the animal property as a Giraffe, we will successfully write a full Giraffe using Giraffe.writeToParcel(), but when we read the parcel, we will use Animal.CREATOR, which won't know anything about the Giraffe properties. This means, though we write a Giraffe into the Parcel, all we can get out will be an Animal.
>
>Unless I'm missing something, I think this means we need to roll back the changes to skip Parcel's readParcelable() and writeParcelable() methods.

**Comment by JakeWharton** [comment]
Perfect. Thanks!

**Pull request merged**
