### PR TITLE
Fix package names being broken by shadow jar plugin

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Compiler turns that into one. Use `"foo".concat("bar")`.

**Comment by SUPERCILEX** [comment]
Can confirm that works, thanks!

**Comment by SUPERCILEX** [comment]
Woot! Do you have an ETA for the next release?

**Comment by rharter** [comment]
I'm travelling for the holiday weekend, so it'll be at least next week sometime.

**Comment by SUPERCILEX** [comment]
SGTM, thanks! 👍

**Comment by rharter** [comment]
0.2.8 is out.

**Comment by SUPERCILEX** [comment]
🎉

**Pull request merged**
