### PR TITLE
Update and shade dependencies

### PR DESCRIPTION
**Pull request by bryanstern**
Current Auto-Value-Parcel leaks dependencies which causes issues with other extensions. Specifically, it leaks AutoValue 1.3, which was causing issues when using this with the AutoValue builder extensions work I had done.

I took the opportunity to update Gradle to make use of the new dependency configurations and updated dependencies to their latest versions as well.

### CODE REVIEW

**Comment by JakeWharton** [comment]
There's no shading going on here. `api` vs. `implement` only have an effect inside a project for compilation avoidance. In the exported pom you'll still get these as "compile" dependencies.

**Comment by bryanstern** [comment]
Maybe I'm using the wrong terminology here, but my understanding is that `api` will reveal that dependency to consumers of the library where `implementation` will not.

>  The `api` configuration should be used to declare dependencies which are exported by the library API, whereas the `implementation` configuration should be used to declare dependencies which are internal to the component.

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by JakeWharton** [comment]
Yes, consumers in the same project (i.e., in this repo). Not consumers pulling the artifact from Maven central.

**Comment by bryanstern** [comment]
That doesn't seem to match my experience consuming this change via jitpack. Will look into this further.

**Comment by JakeWharton** [comment]
If that's the case then dependencies are simply being left out of the pom which will be incorrect.

**Comment by bryanstern** [comment]
I'm going to close this out. Turns out the transitive dependency issues were in my project rather than this one.

**Pull request closed without merging**
